//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.0
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfClient.ClaimsAwareWebServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClaimsAwareWebServices.IClaimsAwareWebService")]
    public interface IClaimsAwareWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClaimsAwareWebService/ComputeResponse", ReplyAction="http://tempuri.org/IClaimsAwareWebService/ComputeResponseResponse")]
        string ComputeResponse(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClaimsAwareWebService/ComputeResponse", ReplyAction="http://tempuri.org/IClaimsAwareWebService/ComputeResponseResponse")]
        System.Threading.Tasks.Task<string> ComputeResponseAsync(string input);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClaimsAwareWebServiceChannel : global::WcfClient.ClaimsAwareWebServices.IClaimsAwareWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClaimsAwareWebServiceClient : System.ServiceModel.ClientBase<global::WcfClient.ClaimsAwareWebServices.IClaimsAwareWebService>, global::WcfClient.ClaimsAwareWebServices.IClaimsAwareWebService {
        
        public ClaimsAwareWebServiceClient() {
        }
        
        public ClaimsAwareWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClaimsAwareWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClaimsAwareWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClaimsAwareWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ComputeResponse(string input) {
            return base.Channel.ComputeResponse(input);
        }
        
        public System.Threading.Tasks.Task<string> ComputeResponseAsync(string input) {
            return base.Channel.ComputeResponseAsync(input);
        }
    }
}
