//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.0
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfClient.CustomerServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/WCFHost")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CusomerAddresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CusomerPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CusomerAddres {
            get {
                return this.CusomerAddresField;
            }
            set {
                if ((object.ReferenceEquals(this.CusomerAddresField, value) != true)) {
                    this.CusomerAddresField = value;
                    this.RaisePropertyChanged("CusomerAddres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CusomerPhone {
            get {
                return this.CusomerPhoneField;
            }
            set {
                if ((this.CusomerPhoneField.Equals(value) != true)) {
                    this.CusomerPhoneField = value;
                    this.RaisePropertyChanged("CusomerPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomerServices.ICustomerService")]
    public interface ICustomerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetCusomerName", ReplyAction="http://tempuri.org/ICustomerService/GetCusomerNameResponse")]
        global::WcfClient.CustomerServices.GetCusomerNameResponse GetCusomerName(global::WcfClient.CustomerServices.GetCusomerNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetCustomer", ReplyAction="http://tempuri.org/ICustomerService/GetCustomerResponse")]
        global::WcfClient.CustomerServices.GetCustomerResponse GetCustomer(global::WcfClient.CustomerServices.GetCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetAllCustomerList", ReplyAction="http://tempuri.org/ICustomerService/GetAllCustomerListResponse")]
        global::WcfClient.CustomerServices.GetAllCustomerListResponse GetAllCustomerList(global::WcfClient.CustomerServices.GetAllCustomerListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCusomerName", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCusomerNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string customercode;
        
        public GetCusomerNameRequest() {
        }
        
        public GetCusomerNameRequest(string customercode) {
            this.customercode = customercode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCusomerNameResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCusomerNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetCusomerNameResult;
        
        public GetCusomerNameResponse() {
        }
        
        public GetCusomerNameResponse(string GetCusomerNameResult) {
            this.GetCusomerNameResult = GetCusomerNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCustomer", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WcfClient.CustomerServices.Customer customer;
        
        public GetCustomerRequest() {
        }
        
        public GetCustomerRequest(WcfClient.CustomerServices.Customer customer) {
            this.customer = customer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCustomerResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WcfClient.CustomerServices.Customer GetCustomerResult;
        
        public GetCustomerResponse() {
        }
        
        public GetCustomerResponse(WcfClient.CustomerServices.Customer GetCustomerResult) {
            this.GetCustomerResult = GetCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllCustomerList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllCustomerListRequest {
        
        public GetAllCustomerListRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllCustomerListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllCustomerListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WcfClient.CustomerServices.Customer[] GetAllCustomerListResult;
        
        public GetAllCustomerListResponse() {
        }
        
        public GetAllCustomerListResponse(WcfClient.CustomerServices.Customer[] GetAllCustomerListResult) {
            this.GetAllCustomerListResult = GetAllCustomerListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerServiceChannel : global::WcfClient.CustomerServices.ICustomerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerServiceClient : System.ServiceModel.ClientBase<global::WcfClient.CustomerServices.ICustomerService>, global::WcfClient.CustomerServices.ICustomerService {
        
        public CustomerServiceClient() {
        }
        
        public CustomerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public global::WcfClient.CustomerServices.GetCusomerNameResponse GetCusomerName(global::WcfClient.CustomerServices.GetCusomerNameRequest request) {
            return base.Channel.GetCusomerName(request);
        }
        
        public global::WcfClient.CustomerServices.GetCustomerResponse GetCustomer(global::WcfClient.CustomerServices.GetCustomerRequest request) {
            return base.Channel.GetCustomer(request);
        }
        
        public global::WcfClient.CustomerServices.GetAllCustomerListResponse GetAllCustomerList(global::WcfClient.CustomerServices.GetAllCustomerListRequest request) {
            return base.Channel.GetAllCustomerList(request);
        }
    }
}
